version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mypassword

  node:
    links:
     - db
    build: .
    volumes:
      - "./myapp:/var/www/node"
    ports:
      - "8082:8082"

volumes:
    db_data:
