version: '2'
services: 
  web:
    image: wordpress
    ports: 
    - "8083:80"
    environment:
      WORDPRESS_DB_HOST: mysql 
      WORDPRESS_DB_PASSWORD: mypaass
      WORDPRESS_DB_USER: root
    links:
    - mysql
      
      
  mysql: 
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mypaass
      MYSQL_DATABASE: mydb
    volumes: 
    - mysql-db:/var/lib/mysql
    
volumes: 
  mysql-db: 
