version: "3"
services:
  web1:
    image: nginx:latest
    ports:
     - "90:80"
   networks:
   - developergroup
   - devopsgroup

  web2:
    image: nginx:latest
    ports:
     - "88:80"
    networks:
      - developergroup
  web3:
    image: nginx:latest
    ports:
     - "89:80"
    networks:
      - devopsgroup

networks:
  devopsgroup:
    driver: devops
  deveopergroup:
    driver: devops

